on:
  push:
    branches: [ main ]
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NodeJS app to my EC2
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.HOST}}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}	
          passphrase: ${{ secrets.passphrase }}	
          port: ${{secrets.PORT}}	
          script: |
            cd /root/nodeapp/NodeJS-URL-Shortener-Microservice
            git pull
            npm install # install dependencies
            pm2 restart index
